#!/bin/env python3
"""
This script diffs the allow, deny, and undefined commands between two files containing
the command lists of the OpenStack CLI generated by the allow-deny-list.py script.

Ignore commands are not shown in the diff.

Undefined commands are shown in the diff if they have changed. If they have not changed but
there are undefined commands, the script will exit with an error since unknown commands should
not be present..
"""

import sys

import yaml

RIGHT_GROUP_MSG = "confirm new commands are in the right group"
UNDEFINED_COMMANDS_MSG = "check ACCEPT_COMMANDS, REJECT_COMMANDS, and IGNORE_COMMANDS"


def show_diff(
    list_name: str, data_1: list[str], data_2: list[str], change_msg: str
) -> None:
    in_list_1_not_in_list_2 = set(data_1[list_name]) - set(data_2[list_name])
    in_list_2_not_in_list_1 = set(data_2[list_name]) - set(data_1[list_name])

    msg = ""
    if in_list_1_not_in_list_2:
        msg += "\n< " + "\n<".join(sorted(in_list_1_not_in_list_2))

    if in_list_2_not_in_list_1:
        msg += "\n> " + "\n>".join(sorted(in_list_2_not_in_list_1))

    if msg:
        print(f"{list_name} has changed, {change_msg}:{msg}")
        return True
    return False


def main() -> None:
    if len(sys.argv) != 3:
        print(
            "Usage: diff-allow-deny.py <allow-deny-list-1.yaml> <allow-deny-list-2.yaml>"
        )
        sys.exit(1)

    file_name_1 = sys.argv[1]
    file_name_2 = sys.argv[2]

    with open(file_name_1, "r") as f:
        list_1 = yaml.safe_load(f)
    with open(file_name_2, "r") as f:
        list_2 = yaml.safe_load(f)

    print(
        "Differences between python-openstackclient version "
        f"{list_1['python_osc_version']} and version {list_2['python_osc_version']}"
    )
    changes = show_diff("allow_commands", list_1, list_2, RIGHT_GROUP_MSG)
    changes |= show_diff("deny_commands", list_1, list_2, RIGHT_GROUP_MSG)

    undefined_changes = show_diff(
        "undefined_commands", list_1, list_2, UNDEFINED_COMMANDS_MSG
    )
    changes |= undefined_changes
    if not undefined_changes and list_2["undefined_commands"]:
        print(
            "Undefined commands have not changed, but there are undefined commands, "
            "so ACCEPT_COMMANDS, REJECT_COMMANDS, and IGNORE_COMMANDS need to be "
            f"revised to include them: {sorted(list_2['undefined_commands'])}"
        )
        sys.exit(1)

    if not changes:
        print("No changes found")


if __name__ == "__main__":
    main()
